export const removeDecimals = (number: number, spaces: number) => {
  let formatNumber = number.toString();
  if (formatNumber.indexOf(".") != -1)
    formatNumber = formatNumber.slice(
      0,
      formatNumber.indexOf(".") + spaces + 1
    );
  return Number(formatNumber);
};

/** Function to remplace special charaters and letters of string */
export const formatterNumbers = (baseText) =>
  baseText
    .toString()
    .replace(/[^\w\s]/gi, "")
    .replace(/\D/g, "");

export const countries: any[] = [
  {
    name: "Algeria",
    country_acronym: "DZ",
    code: "+213",
    currency_name: "Algerian Dinar",
    currency_code: "DZD",
  },
  {
    name: "Argentina",
    country_acronym: "AR",
    code: "+54",
    currency_name: "Argentine Peso",
    currency_code: "ARS",
  },
  {
    name: "Australia",
    country_acronym: "AU",
    code: "+61",
    currency_name: "Australian Dollar",
    currency_code: "AUD",
  },
  {
    name: "Austria",
    country_acronym: "AT",
    code: "+43",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Belgium",
    country_acronym: "BE",
    code: "+32",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Bolivia",
    country_acronym: "BO",
    code: "+591",
    currency_name: "Boliviano",
    currency_code: "BOB",
  },
  {
    name: "Brazil",
    country_acronym: "BR",
    code: "+55",
    currency_name: "Brazilian Real",
    currency_code: "BRL",
  },
  // {
  //   name: "Canada",
  //   country_acronym: "CA",
  //   code: "+1",
  //   currency_name: "Canadian Dollar",
  //   currency_code: "CAD",
  // },
  {
    name: "Chile",
    country_acronym: "CL",
    code: "+56",
    currency_name: "Chilean Peso",
    currency_code: "CLP",
  },
  {
    name: "Colombia",
    country_acronym: "CO",
    code: "+57",
    currency_name: "Colombian Peso",
    currency_code: "COP",
  },
  {
    name: "Costa Rica",
    country_acronym: "CR",
    code: "+506",
    currency_name: "Costa Rican Colon",
    currency_code: "CRC",
  },
  {
    name: "Cyprus",
    country_acronym: "CY",
    code: "+537",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Czech Republic",
    country_acronym: "CZ",
    code: "+420",
    currency_name: "Czech Koruna",
    currency_code: "CZK",
  },
  {
    name: "Denmark",
    country_acronym: "DK",
    code: "+45",
    currency_name: "Danish Krone",
    currency_code: "DKK",
  },
  {
    name: "Dominican Republic",
    country_acronym: "DO",
    code: "+1 809",
    currency_name: "Dominican Peso",
    currency_code: "DOP",
  },
  {
    name: "Estonia",
    country_acronym: "EE",
    code: "+372",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Finland",
    country_acronym: "FI",
    code: "+358",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "France",
    country_acronym: "FR",
    code: "+33",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Germany",
    country_acronym: "DE",
    code: "+49",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Great Britain",
    country_acronym: "GB",
    code: "+44",
    currency_name: "Pound Sterling",
    currency_code: "GBP",
  },
  {
    name: "Greece",
    country_acronym: "GR",
    code: "+30",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Hong Kong",
    country_acronym: "HK",
    code: "+852",
    currency_name: "Hong Kong Dollar",
    currency_code: "HKD",
  },
  {
    name: "Iceland",
    country_acronym: "IS",
    code: "+354",
    currency_name: "Iceland Krona",
    currency_code: "ISK",
  },
  {
    name: "India",
    country_acronym: "IN",
    code: "+91",
    currency_name: "Indian Rupee",
    currency_code: "INR",
  },
  {
    name: "Indonesia",
    country_acronym: "ID",
    code: "+62",
    currency_name: "Rupiah",
    currency_code: "IDR",
  },
  {
    name: "Ireland",
    country_acronym: "IE",
    code: "+353",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Israel",
    country_acronym: "IL",
    code: "+972",
    currency_name: "New Israeli Sheqel",
    currency_code: "ILS",
  },
  {
    name: "Italy",
    country_acronym: "IT",
    code: "+39",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Japan",
    country_acronym: "JP",
    code: "+81",
    currency_name: "Yen",
    currency_code: "JPY",
  },
  {
    name: "Laos",
    country_acronym: "Laos",
    code: "+856",
    currency_name: "Kip",
    currency_code: "LAK",
  },
  {
    name: "Latvia",
    country_acronym: "LV",
    code: "+371",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Lithuania",
    country_acronym: "LT",
    code: "+370",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Luxembourg",
    country_acronym: "LU",
    code: "+352",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Malaysia",
    country_acronym: "MY",
    code: "+60",
    currency_name: "Malaysian Ringgit",
    currency_code: "MYR",
  },
  {
    name: "Mexico",
    country_acronym: "MX",
    code: "+52",
    currency_name: "Mexican Peso",
    currency_code: "MXN",
  },
  {
    name: "Nepal",
    country_acronym: "NP",
    code: "+977",
    currency_name: "Nepalese Rupee",
    currency_code: "NPR",
  },
  {
    name: "New Zealand",
    country_acronym: "NZ",
    code: "+64",
    currency_name: "New Zealand Dollar",
    currency_code: "NZD",
  },
  {
    name: "Norway",
    country_acronym: "NO",
    code: "+47",
    currency_name: "Norwegian Krone",
    currency_code: "NOK",
  },
  {
    name: "Paraguay",
    country_acronym: "PY",
    code: "+595",
    currency_name: "Guarani",
    currency_code: "PYG",
  },
  {
    name: "Peru",
    country_acronym: "PE",
    code: "+51",
    currency_name: "Nuevo Sol",
    currency_code: "PEN",
  },
  {
    name: "Philippines",
    country_acronym: "PH",
    code: "+63",
    currency_name: "Philippine Peso",
    currency_code: "PHP",
  },
  {
    name: "Poland",
    country_acronym: "PL",
    code: "+48",
    currency_name: "Zloty",
    currency_code: "PLN",
  },
  {
    name: "Portugal",
    country_acronym: "PT",
    code: "+351",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Singapore",
    country_acronym: "SG",
    code: "+65",
    currency_name: "Singapore Dollar",
    currency_code: "SGD",
  },
  {
    name: "Slovakia",
    country_acronym: "SK",
    code: "+421",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Slovenia",
    country_acronym: "SI",
    code: "+386",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "South Africa",
    country_acronym: "ZA",
    code: "+27",
    currency_name: "Rand",
    currency_code: "ZAR",
  },
  {
    name: "South Korea",
    country_acronym: "KR",
    code: "+82",
    currency_name: "South Korean won",
    currency_code: "KRW",
  },
  {
    name: "Spain",
    country_acronym: "ES",
    code: "+34",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Sweden",
    country_acronym: "SE",
    code: "+46",
    currency_name: "Swedish Krona",
    currency_code: "SEK",
  },
  {
    name: "Switzerland",
    country_acronym: "CH",
    code: "+41",
    currency_name: "Swiss Franc",
    currency_code: "CHF",
  },
  {
    name: "Tanzania",
    country_acronym: "TZ",
    code: "+255",
    currency_name: "Tanzanian",
    currency_code: "TZS",
  },
  {
    name: "Thailand",
    country_acronym: "TH",
    code: "+66",
    currency_name: "Baht",
    currency_code: "THB",
  },
  {
    name: "The Netherlands",
    country_acronym: "NL",
    code: "+31",
    currency_name: "Euro",
    currency_code: "EUR",
  },
  {
    name: "Turkey",
    country_acronym: "TR",
    code: "+90",
    currency_name: "Turkish Lira",
    currency_code: "TRY",
  },
  {
    name: "United States",
    country_acronym: "US",
    code: "+1",
    currency_name: "US Dollar",
    currency_code: "USD",
  },
  {
    name: "Vietnam",
    country_acronym: "VN",
    code: "+84",
    currency_name: "Vietnamese Dong",
    currency_code: "VND",
  },
];
